keywords = {
    'Regeneration': "The unit heals this amount during the combat phase. Regeneration is applied before checking for death.",
    'After Combat': "An effect that triggers after the Combat Phase.",
    'Aura': "An effect which applies to units when they enter a specified area and is removed when they leave.",
    'Bounce': "Return target to owners fountain if it's a hero, or the hand if it's a creep or item.",
    'Burn': "Remove mana from the enemy player.",
    'Cleave': "During the combat phase, deal Cleave damage to all adjacent enemies. Cleave damage doesn't hit towers.",
    'Cross Lane': "Cross Lane cards are cast by heroes in one lane, but can target objects in a different lane.",
    'Cursed': "Destroyed when replaced by another item.",
    'Death Effect': "An effect that is processed after this unit dies.",
    'Decay': "This unit will take extra damage in combat. Ignores armor entirely.",
    'Devour': "When this unit is placed on top of another unit, it gains that unit's Attack and Health.",
    'Disarm': "A disarmed unit does not attack its target during battles. Lasts until the end of round by default.",
    'Dispel': "Remove an enchantment.",
    'Enchant': "An enchantment lasts until dispelled, remaining even through death.",
    'Feeble': "When a unit deals Attack damage to this unit in combat, excess damage is dealt to your tower.",
    'Fountain': "When heroes die they are placed in the Fountain zone for a full round before becoming ready to redeploy. When heroes enter the Fountain they are fully healed and temporary effects on them are purged.",
    'Jump': "Select a new target for this effect.",
    'Lifesteal': "This unit heals equal to its Attack if it survives a combat in which it damaged another unit.",
    'Lock': "Cards cannot be played as long as they are locked. Lock is applied for a duration in rounds. At the end of a round, all locked cards lose 1 Lock. Locked cards are revealed.",
    'Minion': "An effect which applies to this unit when adjacent to an allied hero.",
    'Mulch': "When this card is played draw a card from your deck which costs less mana.",
    'Pierce': "Piercing damage is not reduced by the target's armor.",
    'Piercing': "Piercing damage is not reduced by the target's armor.",
    'Pillager': "This unit steals 2 gold from the opponent whenever it damages their tower.",
    'Play Effect': "An additional effect that is processed at the time you play this creep.",
    'Purge': "Removes modifications and temporary effects, but not damage. Purging does not affect base abilities or external effects, such as those from equipped items and continuous effects from auras.",
    'Push': "Move a unit 1 slot randomly left or right to an occupied spot.",
    'Quickcast': "After you play this, you get the initiative coin and may immediately take another action. If you use this action to pass, you will retain initiative and may act first next round.",
    'Quickstrike': "Units with quickstrike attack before units without quickstrike. Regeneration and decay are applied at the same time as combat damage, after quickstrike damage resolves.",
    'Reflect': "When targeted or attacked, damage that would be done to this unit is instead dealt to the caster or attacker.",
    'Retaliate': "When attacked during a battle (even outside of the combat phase), deal this much extra damage to the attackers.",
    'Rooted': "Can't be moved.",
    'Scheme': "An effect which triggers when the card's owner passes.",
    'Siege': "During the combat phase, deal Siege damage to the enemy tower.",
    'Sneak Attack': "A unit deals its Attack damage to its target in a one-way battle. Combat attributes such as Armor, Retaliate, and Piercing are applied.",
    'Stun': "A stunned unit is silenced (cannot use any active abilities and cannot be used to play cards of its color) and disarmed (does not attack its target during battles). Lasts until the end of round by default.",
    'Swap': "Move a unit to the targeted slot. If that slot was occupied, the unit in that space move to the original unit's position.",
    'Tower Enchantment': "A tower enchantment is a spell that adds a permanent effect to a tower or lane. Tower enchantments are not units and do not occupy combat positions.",
    'Taunt': "When a unit taunts all of its enemy neighbors change their combat target to that unit. Targets reset after each round.",
    'Trample': "This unit deals excess Attack damage to the tower when it battles in combat.",
    'Untargetable': "Can't be targeted by enemy spells of abilities."
}